### ISSUE TITLE
we need intersectionAll.json

### ISSUE THREAD

**Issue by rguitiayoub** [htkcodes/pairGen#4]
after installing packages and trying to run the script using 'node genPair.js' I found this issue 
pairGen>node genPair.js
setAdd: 25.622ms
writing intersection
done
(node:9180) UnhandledPromiseRejectionWarning: Error: connection not open on send()
    at Object.ConnectionError (C:\Users\ayoub\node_modules\web3-providers-ws\node_modules\web3-core-helpers\lib\errors.js:66:23)
    at Object.ConnectionNotOpenError (C:\Users\ayoub\node_modules\web3-providers-ws\node_modules\web3-core-helpers\lib\errors.js:49:21)
    at C:\Users\ayoub\node_modules\web3-providers-ws\lib\index.js:155:37
    at Map.forEach (<anonymous>)
    at WebsocketProvider._onClose (C:\Users\ayoub\node_modules\web3-providers-ws\lib\index.js:154:27)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Users\ayoub\node_modules\yaeti\lib\EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (C:\Users\ayoub\node_modules\websocket\lib\W3CWebSocket.js:219:14)
    at WebSocketClient.<anonymous> (C:\Users\ayoub\node_modules\websocket\lib\W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:400:28)
    at ClientRequest.handleRequestError (C:\Users\ayoub\node_modules\websocket\lib\WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by htkcodes** [comment]
That has to do with your provider not the code.
